Johana Tellez-Michael Caicedo
##Preparación de datos

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

# Número de ejemplos
n = 50000

# Listas para guardar los datos
X = []  # Entradas (valores de A y B)
y = []  # Salidas (resultado C = A×B)

for _ in range(n):
    # Generar matrices 2x2 con valores aleatorios entre -20 y 20
    A = np.random.randint(-20, 21, (2, 2))
    B = np.random.randint(-20, 21, (2, 2))

    # Calcular el resultado
    C = np.dot(A, B)

    # Guardar datos
    X.append(np.concatenate((A.flatten(), B.flatten())))  # 8 valores de entrada
    y.append(C.flatten())  # 4 valores de salida

# Convertir listas a arrays de numpy
X = np.array(X)
y = np.array(y)

# Dividir en 70% entrenamiento y 30% prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Tamaño de los conjuntos:")
print("Entrenamiento:", X_train.shape, y_train.shape)
print("Prueba:", X_test.shape, y_test.shape)



Tamaño de los conjuntos:
Entrenamiento: (35000, 8) (35000, 4)
Prueba: (15000, 8) (15000, 4)


##Codigo para entrenar el modelo y probarlo

In [6]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Crear el pipeline: genera las combinaciones entre variables (grado 2) + regresión lineal
modelo = make_pipeline(
    PolynomialFeatures(degree=2, include_bias=False),
    LinearRegression()
)

# Entrenar el modelo con los datos de entrenamiento
modelo.fit(X_train, y_train)

# Evaluar el modelo con los datos de prueba
y_pred = modelo.predict(X_test)

# Calcular métricas de rendimiento
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Evaluación del modelo (con PolynomialFeatures):")
print(f"Error cuadrático medio (MSE): {mse:.10f}")
print(f"Coeficiente de determinación (R²): {r2:.10f}")

# Mostrar algunas comparaciones reales vs predichas, incluyendo matrices A y B
for i in range(4):
    print(f"\nEjemplo {i+1}")

    # Reconstruir matrices A y B desde los 8 valores de entrada
    entrada = X_test[i]
    A = entrada[:4].reshape(2, 2)
    B = entrada[4:].reshape(2, 2)

    print("Matriz A:")
    print(A)
    print("Matriz B:")
    print(B)

    print("Predicho (C = A × B):")
    print(np.round(y_pred[i].reshape(2, 2), 2))
    print("Real (C verdadero):")
    print(y_test[i].reshape(2, 2))
    print("-" * 40)


Evaluación del modelo (con PolynomialFeatures):
Error cuadrático medio (MSE): 0.0000000000
Coeficiente de determinación (R²): 1.0000000000

Ejemplo 1
Matriz A:
[[-13  -7]
 [ 16 -18]]
Matriz B:
[[ 6  6]
 [19 13]]
Predicho (C = A × B):
[[-211. -169.]
 [-246. -138.]]
Real (C verdadero):
[[-211 -169]
 [-246 -138]]
----------------------------------------

Ejemplo 2
Matriz A:
[[-11  20]
 [ -8   5]]
Matriz B:
[[  6  15]
 [ 19 -12]]
Predicho (C = A × B):
[[ 314. -405.]
 [  47. -180.]]
Real (C verdadero):
[[ 314 -405]
 [  47 -180]]
----------------------------------------

Ejemplo 3
Matriz A:
[[-1  2]
 [-8 20]]
Matriz B:
[[-20   3]
 [ 20  -9]]
Predicho (C = A × B):
[[  60.  -21.]
 [ 560. -204.]]
Real (C verdadero):
[[  60  -21]
 [ 560 -204]]
----------------------------------------

Ejemplo 4
Matriz A:
[[ 12 -13]
 [-16  15]]
Matriz B:
[[10 13]
 [10 -1]]
Predicho (C = A × B):
[[ -10.  169.]
 [ -10. -223.]]
Real (C verdadero):
[[ -10  169]
 [ -10 -223]]
----------------------------------------


##Análisis de resultados
El modelo de regresión potenciado con características polinómicas de segundo grado demostró un desempeño sobresaliente en la predicción de los resultados de la multiplicación de matrices 2×2. Las métricas obtenidas reflejan un error cuadrático medio prácticamente nulo y un coeficiente de determinación cercano a uno, lo que evidencia que el modelo logró aprender con gran precisión la relación matemática existente entre las variables de entrada y salida